# Homework 12

https://scikit-learn.org/0.15/modules/scaling_strategies.html#incremental-learning

* Implement a mini batch functionality to train a regressor.
    - (Optional) If anyone want to do this in a pipeline can do this: https://koaning.github.io/tokenwiser/api/pipeline.html

* Save model, load the model again and test it on `X_test` __Do NOT commit the pickle file__

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
def test_df():
    df = pd.read_csv('https://raw.githubusercontent.com/msaricaumbc/DS_data/master/ds602/car_prices/car_prices.csv', low_memory=False)

    df = df.sample(5000, random_state=100).reset_index(drop=True)
    
    y = df['sellingprice']
    df.drop('sellingprice', axis=1, inplace=True)
    X = df
    
    return X,y

def partial_df():
    df = pd.read_csv('https://raw.githubusercontent.com/msaricaumbc/DS_data/master/ds602/car_prices/car_prices.csv', low_memory=False)
   
    while(True):
        yield df.sample(100).reset_index(drop=True)
        
gen = partial_df()

In [ ]:
X_test, y_test = test_df()

In [9]:
# each time you call this you will get a new slice of the dataframe.
next(gen)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2010,Toyota,Camry,LE,Sedan,automatic,4t4bf3ek8ar033021,mn,3.9,70852.0,gray,gray,capital one auto finance,9600,9900,Wed Feb 25 2015 02:30:00 GMT-0800 (PST)
1,2013,Hyundai,Tucson,GL,SUV,automatic,km8jt3ab8du591248,ca,4.4,36732.0,gray,black,hyundai motor america/co car,14450,15400,Tue Jan 13 2015 12:00:00 GMT-0800 (PST)
2,2014,Chrysler,Town and Country,Touring,Minivan,automatic,2c4rc1bg0er381893,nj,1,17413.0,black,black,enterprise vehicle exchange / tra / rental / t...,19650,12000,Wed Feb 04 2015 04:00:00 GMT-0800 (PST)
3,2012,Kia,Forte,EX,Sedan,automatic,knafu4a2xc5549764,ga,3.4,41375.0,gray,gray,prestige financial services,9000,7500,Tue Feb 03 2015 01:30:00 GMT-0800 (PST)
4,2012,Toyota,Corolla,LE,sedan,automatic,5yfbu4ee3cp048126,tx,3.6,56129.0,black,beige,the hertz corporation,9000,9000,Wed Jun 10 2015 03:05:00 GMT-0700 (PDT)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2013,Ford,F-150,XLT,SuperCrew,automatic,1ftfw1efxdkf73462,ne,2.9,19123.0,white,gray,enterprise vehicle exchange/davenport,27000,26800,Thu Dec 18 2014 10:30:00 GMT-0800 (PST)
96,2014,Toyota,Camry,SE,sedan,automatic,4t1bf1fk4eu789173,fl,1.9,21114.0,gray,black,east coast financial,15850,13500,Fri Jun 05 2015 02:15:00 GMT-0700 (PDT)
97,2003,Chevrolet,Monte Carlo,LS,Coupe,automatic,2g1ww12e039167419,oh,NaN,168398.0,yellow,gray,colonial auto sales,1500,1650,Tue Dec 23 2014 09:30:00 GMT-0800 (PST)
98,2013,Ford,Fusion,S,Sedan,automatic,3fa6p0g79dr320325,oh,4.8,8180.0,red,gray,"ford motor credit company,llc",13850,14100,Tue Jan 27 2015 01:00:00 GMT-0800 (PST)
99,2013,Dodge,Durango,SXT,SUV,automatic,1c4rdhag9dc672570,tx,3.8,28465.0,black,—,chrysler capital,21400,21700,Wed Jan 14 2015 02:00:00 GMT-0800 (PST)